print("Hello, World!")
print("Hello, Pyhon!")
print ("Richard")
print("The itsy bitsy spider climbed up the waterspout.")
print("Down came the rain and washed the spider out.")
print("The itsy bitsy spider climbed up the waterspout.")
print()
print("Down came the rain and washed the spider out.")
print("The itsy bitsy spider\nclimbed up the waterspout.")
print()
print("Down came the rain\nand washed the spider out.")
print("The itsy bitsy spider" , "climbed up" , "the waterspout.")
print("My name is", "Python.")
print("Monty Python.")
print("My name is", "Python.", end=" ")
print("Monty Python.")
print("My name is ", end="")
print("Monty Python.")
print("My", "name", "is", "Monty", "Python.", sep="-")
print("My", "name", "is", "Monty", "Python.", sep="*")
print("My", "name", "is", "Monty", "Python.", sep="TEST")
print("My", "name", "is", sep="_", end="*")
print("Monty", "Python.", sep="*", end="*\n")
print()
print()
print("EXERCISE 1")
print()
print("Programming","Essentials","in", sep="***", end="...")
print("Python", end="\n")
print("EXERCISE 2")
print()
print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")
print()
print("EXERCISE WIDER ARROW")
print()
print("     *")
print("   *   *")
print("  *     *")
print(" *       *")
print("***     ***")
print("  *     *")
print("  *     *")
print("  *******")
print()
print("EXERCISE TWICE AS LARGE ARROW")
print()
print("        *")
print()
print("    *      *")
print()
print("   *        *")
print()
print("  *          *")
print()
print("***          ***")
print()
print("  *         *")
print()
print("  *         *")
print()
print("  ***********")
print()
print("        *")
print("       * *")
print("      *   *")
print("     *     *")
print("    *       *")
print("   *         *")
print("  *           *")
print(" *             *")
print("***           ***")
print("  *          *")
print("  *          *")
print("  *          *")
print("  *          *")
print("  *          *")
print("  ************")
print("EXERCISE MINIMISE NUMBER OF FUNCTIONS")
print("    */n   * */n  *   */n *     */n***   ***/n  *   */n  *   */n  *****")
print("EXERCISE MINIMISE NUMBER OF FUNCTIONS retake")
print("    *\n   * *\n  *   *\n *     *\n***   ***\n  *   *\n  *   *\n  *****")
print("EXERCISE DUPLICATE ARROWS")
print()
print("    *", "    *", sep="               ")
print("   * *", "   * *", sep="               ")
print("  *   *", "  *   *", sep="               ")
print(" *     *", " *     *", sep="               ")
print("***   ***", "***   ***", sep="               ")
print("  *   *", "  *   *", sep="               ")
print("  *   *", "  *   *", sep="               ")
print("  *****", "  *****", sep="               ")
print()
print("EXERCISE DUPLICATE ARROWS RESHOW")
print()
print("    *", "        *", sep="               ")
print("   * *", "      * *", sep="               ")
print("  *   *", "    *   *", sep="               ")
print(" *     *", "  *     *", sep="               ")
print("***   ***", "***   ***", sep="               ")
print("  *   *", "    *   *", sep="               ")
print("  *   *", "    *   *", sep="               ")
print("  *****", "    *****", sep="               ")
print()
print("EXERCISE DUPLICATE ARROWS test")
print()
print("    *" * 3)
print("   * *"* 3)
print("  *   *"* 3)
print(" *     *"* 3)
print("***   ***"* 3)
print("  *   *"* 3)
print("  *   *"* 3)
print("  *****"* 3)
print()
print()
print("    *        "* 3)
print("   * *       "* 3)
print("  *   *      "* 3)
print(" *     *     "* 3)
print("***   ***    "* 3)
print("  *   *      "* 3)
print("  *   *      "* 3)
print("  *****      "* 3)
print()
print("EXERCISE TESTING")
print()
Print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")
print()